// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tienda_electrodomesticos.Models;

#nullable disable

namespace tienda_electrodomesticos.Migrations
{
    [DbContext(typeof(TiendaElectrodomesticosDbContext))]
    [Migration("20260330065759_ShoppingCartAdded")]
    partial class ShoppingCartAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("tienda_electrodomesticos.Models.Appliance", b =>
                {
                    b.Property<int>("ApplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InStock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApplianceOfTheWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.HasKey("ApplianceId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("tienda_electrodomesticos.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("tienda_electrodomesticos.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApplianceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("TEXT");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ApplianceId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("tienda_electrodomesticos.Models.Appliance", b =>
                {
                    b.HasOne("tienda_electrodomesticos.Models.Category", "Category")
                        .WithMany("Appliances")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("tienda_electrodomesticos.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("tienda_electrodomesticos.Models.Appliance", "Appliance")
                        .WithMany()
                        .HasForeignKey("ApplianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appliance");
                });

            modelBuilder.Entity("tienda_electrodomesticos.Models.Category", b =>
                {
                    b.Navigation("Appliances");
                });
#pragma warning restore 612, 618
        }
    }
}
